### ISSUE TITLE
Wheels rotating

### ISSUE THREAD

**Issue by McQueenPL** [digicreatures/rigacar#2]
Is there any possibility to make wheel spin always in one direction?

**Comment by spoonless** [comment]
Not sure to understand your need... you would like to limit rotation of wheels ? Please describe more precisely your issue.
By the way, version 2 is almost ready (only documentation to be updated). I encourage you to try it because I fixed many things and I improved the generated rig.
https://github.com/digicreatures/rigacar/tree/v2

**Comment by McQueenPL** [comment]
Thank you for answer!

I'm trying to make simple car animation and I think you addon is fine for
it and future applications, but unfortunately found that car wheels are
turning in reverse direction at middle of the "way", appending a small
video of this, I don't know it's mine or addon mistake. Of course, using
latest version. For fast moving car this is not bad, but I want to have
slow mo of car wheels from the same animation (less work to do, as I can
render various animations from one file).

Maybe there's workaround of that, but I didn't find that.

Regards, Łukasz


2018-03-11 2:25 GMT+01:00 David Gayerie <notifications@github.com>:

**Comment by spoonless** [comment]
Ok now I get it. Actually, it's not related to rigacar. It is most probably an optical illusion you can observe in real life.
https://io9.gizmodo.com/why-do-wheels-sometimes-appear-to-spin-backwards-1593807400
But it is quite disturbing in CG because you tend to consider it as fake... but it is optically correct. I already faced this problem and I only see two solutions :
1) try to enable motion blur to have a realistic rendering. It will not remove the effect but it will had visual information the wheel is rotating at high speed. Unfortunately it will cost you extra time of rendering
2) cheat (my favorite) ! This effect appears at certain speeds... so avoid to make sequence showing wheels when the car reach these speeds.

**Comment by McQueenPL** [comment]
So, only way is cheating :) Thanks!

2018-03-11 22:07 GMT+01:00 David Gayerie <notifications@github.com>:

**Comment by spoonless** [comment]
I am eager to see your animation... please share (if possible)
