### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Wotisrv** [digicreatures/rigacar#20]
Not an issue but a question: Is this project still alive?

**Comment by spoonless** [comment]
yes... and no.
I haven't planned any new feature. 
I haven't time to take closer look at requests and comments. Unfortunately I saw some of them seems related to broken API of Blender itself (especially animation baking API which is a real nightmare since blender 2.8x series).
For the time being, I only expect to check and fix (if necessary) the addon for blender 2.83 (which will be the first LTS).
