### ISSUE TITLE
Installing Rigacar in Blender 2.79b

### ISSUE THREAD

**Issue by SupercarHunter** [digicreatures/rigacar#34]
I'm currently trying to install Rigacar into Blender 2.79b. The Add-ons tab recognizes it, but it keeps giving me errors about importing it and getting it to be activated.

The error is about Traceback (most recent call last)

Any solutions how to fix this?

**Comment by spoonless** [comment]
Rigacar v6 is only for Blender 2.83 and up. Blender does not prevent you from installing a none compliant add-on (you just still have a warning message after a successful activation). Unfortunately, there are many evolutions since Blender v2.80 so there is no backward compatibility for 2.79

For blender 2.79, you can download Rigacar version v4.1
https://github.com/digicreatures/rigacar/releases/tag/b2.80v4.1
But this version is not maintained anymore.

Of course, I recommend you upgrading to the latest Blender version but I suppose you have very good reasons not to.
