### ISSUE TITLE
rig doesn't appear

### ISSUE THREAD

**Issue by samegud** [digicreatures/rigacar#5]
![Capture](https://user-images.githubusercontent.com/49999604/56770875-66073280-67b5-11e9-86dd-20ce53193255.PNG)
hello,  thanks for the add-on and the tutorial its very helpful. but everytime i try to generate the rig this happen. no rig shows up . only this bones. any advice?

**Comment by spoonless** [comment]
When you get this mess of bones, it means an error occurred during the generation. Please make sure you use the latest build of blender 2.80. Previous builds are obsolete because developers have changed the Python API.
If you have the same issue with the latest build, can you get any error message ? or can you share your file ?
