### ISSUE TITLE
Wheel Steering Issue 

### ISSUE THREAD

**Issue by Phoenix8029** [digicreatures/rigacar#69]
![image](https://user-images.githubusercontent.com/107860304/174604128-13186073-8ae4-4420-899d-d8caf772b8de.png)
Hi, im facing an issue where the front right wheel is not turning in a proper manner. ive tried many times to fix but i couldnt. Any way to fix this?

**Comment by spoonless** [comment]
Many issues can explain this situation.
* check your model is positioned as if the car is on the grid. It is important for Rigacar to estimate the dimension of the car. I am not sure but your model seems to float over the grid.
* check the scale factor of all your objects. It should be (1,1,1). Applying scale is highly recommended on rigged objects.
* check the bounding box of your objects. Sometimes we miss an orphan vertex floating somewhere and it has an impact on the bounding box size. Rigacar uses the bounding box size to discover the size of each objects.
* check the origin points of your objects. For the wheels, it should be on the rotation axis of the wheel
If you find something wrong based on that list, please remove the rig, fix the model and create it again.
Otherwise, if you can share your blend file, I will be able to check it also...

**Comment by tiu47** [comment]
Thanks so much @spoonless.  I had the same issue; a missed vertex inside the wheel, making it  bigger than it should.

![Screenshot_8](https://user-images.githubusercontent.com/1618688/178039199-a9677ebc-7b59-4fa2-a97a-477c7ff7182b.png)
