### ISSUE TITLE
Rigacar broken

### ISSUE THREAD

**Issue by aranya-maji** [digicreatures/rigacar#70]
i rigged 5 cars out of 8 cars with rigacar and all were working perfect. as i reopened the saved blend file, the 5 car got deleted by itself and the remaining 3 cars are not rigging properly. the wheels are not rotating and not steering. Not even the suspension system is visible. Infact it is not detecting the wheels at all. Although i used the same syntax for the names. With those same syntax the 4 remaining rigged cars are working but the remaining 3 are not.

**Comment by spoonless** [comment]
Sorry for that. But Rigacar does not provide a new type of objects in Blender. It is just an automated way to generate a rig. It means that when you save your file, you just save a normal blender rig.
Have you updated blender since you created the original file?  It could explain why the file is broken now.
Have you linked your models from external blend files ? If the files hierarchy has changed (you renamed or move one or several files) then the scene cannot be loaded properly.

**Comment by aranya-maji** [comment]
Yup i found out the problem.
Everytime i finish rigging a car, i will have to uninstall the addon from
blender and then reinstall before i start to rig another car.
That way, it is not causing any trouble, at least not till now.
But thanks for replying.
