### ISSUE TITLE
Pressing T when having the rig selected doesn't show the add car deformation rig toolbar menu

### ISSUE THREAD

**Issue by IronLover64** [digicreatures/rigacar#8]
Instead of having the addon toolbar menu appear when pressing T, it just shows the regular translate toolbar menu.

**Comment by spoonless** [comment]
I found no issue for blender 2.79 and last build of 2.80. Check you have the last version of blender and of rigacar.
In 2.80, the toolbar menu has its own panel named "Rigacar"
In all versions, you have to select/edit/pose a rigacar armature to see the menu

**Comment by IronLover64** [comment]
It's no use, I cannot edit it once I move it

**Comment by spoonless** [comment]
Sorry, you really have to provide more details (screenshots for instance). I cannot figure out the problem.

**Comment by IronLover64** [comment]
![Screenshot (353)](https://user-images.githubusercontent.com/51809607/59770618-62a09c80-9276-11e9-904e-6cc9f5d1d47e.png)
![Screenshot (354)](https://user-images.githubusercontent.com/51809607/59770624-63d1c980-9276-11e9-85e4-c78601e7ae8a.png)
![Screenshot (355)](https://user-images.githubusercontent.com/51809607/59770627-659b8d00-9276-11e9-9ee5-1e79961d84e0.png)

The first picture is before adding the rig
The second is after adding the rig
The third is after moving the rig up the z axis
And how come it displaces my vehicle when I add the rig?

**Comment by IronLover64** [comment]
[tttttArmored_tst - Copy.zip](https://github.com/digicreatures/rigacar/files/3306437/tttttArmored_tst.-.Copy.zip)
Here's the whole file if you need additional information

**Comment by IronLover64** [comment]
And how can you change the delta length and I can't?

**Comment by IronLover64** [comment]
And how did you add the bones without having the model move to another location?

**Comment by spoonless** [comment]
The vehicle moves because rigacar add the armature at the location of the 3D Cursor as it is the common behaviour in blender. In your file :
* the 3D cursor is not correctly located
* the model itself is not correctly located. Rigacar expects your model is layered upon the grid as if it were on the ground. This is not the case for your model.
The delta length cannot be change anymore because it is no longer necessary in Rigacar v4
The rigacar menu is displayed at the bottom of the properties panel (pressing N not T)
Here is the final rig (I parented the antenna to the body)
[tttttArmored_tst - Copy.rigged.blend.zip](https://github.com/digicreatures/rigacar/files/3306958/tttttArmored_tst.-.Copy.rigged.blend.zip)

**Comment by IronLover64** [comment]
Dude, thank you
